spring:
  datasource:
    url: jdbc:postgresql://localhost/prey
    username: zhouminhao
    password: 1q2w3e4r5t

  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/

server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:ssl/bundle.pfx
    key-store-password: 1q2w3e4r5t